import './globals.css';

import classNames from 'classnames';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: `Noodle's House`,
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={'h-full'}
    >
      <body className={classNames(inter.className, 'h-full')}>{children}</body>
    </html>
  );
}
