import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import classNames from 'classnames';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={'h-full'}
    >
      <head>
        <link
          rel="icon"
          href="/favicon/NoodleIcon.svg"
          type="image/svg+xml"
          sizes="any"
        />
      </head>

      <body className={classNames(inter.className, 'h-full')}>{children}</body>
    </html>
  );
}
