name: BuildAndDeploy SWA:ThankfulPebble

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_PEBBLE_0FD322F0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          api_location: 'api'
          # This DOES need to be the command within ^ api
          api_build_command: 'npm run build'
          app_location: '/'
          app_build_command: 'npm i -D "@rollup/rollup-linux-x64-gnu@^4.7.0" && npm run build:swa:ui'
          output_location: 'ui/dist'
          data_api_location: 'swa-db-connections'

        env:
          NOOD_UNSPLASH_ACCESS_KEY: ${{ secrets.NOOD_UNSPLASH_ACCESS_KEY }}
          NOOD_DB_CONNECTION_STRING: ${{ secrets.NOOD_DB_CONNECTION_STRING }}

          NOOD_APPLE_CLIENT_ID: ${{ secrets.NOOD_APPLE_CLIENT_ID }}
          NOOD_APPLE_CLIENT_SECRET: ${{ secrets.NOOD_APPLE_CLIENT_SECRET }}
          NOOD_DB_URL: ${{ secrets.NOOD_DB_URL }}
          NOOD_DB_DATABASE: ${{ secrets.NOOD_DB_DATABASE }}
          NOOD_DB_USER: ${{ secrets.NOOD_DB_USER }}
          NOOD_DB_PASS: ${{ secrets.NOOD_DB_PASS }}
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          app_location: '/' # App source code path
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_PEBBLE_0FD322F0F }}
          action: 'close'
